version: '3.8'

services:
  student:
    image: ananyaabhat/student-service:latest
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: sqlite:////data/students.db
    volumes:
      - student_data:/data

  internship:
    image: teammate2_username/internship-service:latest
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: sqlite:////data/internships.db
    volumes:
      - internship_data:/data

  application:
    image: priya721k/application-service:latest
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: sqlite:////data/applications.db
    volumes:
      - application_data:/data

volumes:
  student_data:
  internship_data:
  application_data: